import React from 'react';
import {
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';

const SECTIONS = [
  {
    heading: '1. Information we collect',
    body: [
      'Farm data you submit: state, crop, farm size in hectares, and optionally rainfall, fertilizer use, and soil quality.',
      'Prediction outputs: generated by our model from the inputs above.',
      'Anonymous technical logs: request timestamps and endpoint names for the purpose of reliability monitoring.',
    ],
  },
  {
    heading: '2. Information we do not collect',
    body: [
      'We do not collect your name, phone number, email address, or any other personal identifier.',
      'We do not collect or store GPS coordinates.',
      'We do not use third-party advertising trackers or analytics SDKs.',
      'We do not sell, rent, or share farm data with brokers or marketers.',
    ],
  },
  {
    heading: '3. Where your data lives',
    body: [
      'On your device: saved predictions are stored locally via AsyncStorage. Clearing the app\'s storage deletes them irreversibly.',
      'On the server: the most recent 500 anonymised predictions may be retained in memory for the rolling /history endpoint. No personally identifying fields are stored.',
    ],
  },
  {
    heading: '4. Your rights',
    body: [
      'You may clear the on-device history at any time from the History screen.',
      'You may operate AgriAI entirely offline; no data leaves your device unless you submit a prediction request.',
      'You may self-host the backend. The source code is open.',
    ],
  },
  {
    heading: '5. Children\'s privacy',
    body: [
      'AgriAI is intended for use by adults engaged in agricultural decision-making. It is not directed at children under 13, and we do not knowingly collect data from them.',
    ],
  },
  {
    heading: '6. Changes to this policy',
    body: [
      'Material changes will be published on this page with a new effective date and announced in the project\'s GitHub repository release notes.',
    ],
  },
  {
    heading: '7. Contact',
    body: [
      'Questions or data requests: durujulietchinenye@gmail.com',
      'GitHub issues: github.com/JulietChinenyeDuru/agriAI-insights',
    ],
  },
];

export default function PrivacyScreen() {
  return (
    <ScrollView style={styles.scroll} contentContainerStyle={styles.container}>

      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <Text style={styles.headerMeta}>Effective date: 23 May 2026 · Maintainer: Juliet Chinenye Duru</Text>
      </View>

      {/* Principle statement */}
      <View style={styles.principle}>
        <Text style={styles.principleText}>
          AgriAI is built around the principle that a farmer's data belongs to the farmer.
          This policy applies to the AgriAI mobile application and the AgriAI backend API.
        </Text>
      </View>

      {/* Policy sections */}
      {SECTIONS.map((s) => (
        <View key={s.heading} style={styles.section}>
          <Text style={styles.sectionHeading}>{s.heading}</Text>
          {s.body.map((line, i) => (
            <View key={i} style={styles.bulletRow}>
              <Text style={styles.bulletDot}>·</Text>
              <Text style={styles.bulletText}>{line}</Text>
            </View>
          ))}
        </View>
      ))}

      {/* Footer */}
      <View style={styles.footer}>
        <Text style={styles.footerText}>
          AgriAI Insights · Open source · MIT licence
        </Text>
      </View>

    </ScrollView>
  );
}

const styles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: '#F1F8E9' },
  container: {
    maxWidth: Platform.select({ web: 760, default: undefined }),
    alignSelf: Platform.select({ web: 'center', default: undefined }),
    width: '100%',
    paddingHorizontal: 20,
    paddingBottom: 48,
  },

  /* Header */
  header: {
    paddingTop: 28,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#DCEDC8',
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1B5E20',
    marginBottom: 6,
  },
  headerMeta: { fontSize: 12, color: '#546E7A' },

  /* Principle */
  principle: {
    backgroundColor: '#E8F5E9',
    borderRadius: 10,
    padding: 16,
    borderLeftWidth: 4,
    borderLeftColor: '#2E7D32',
    marginBottom: 24,
  },
  principleText: {
    fontSize: 14,
    color: '#1B5E20',
    lineHeight: 22,
    fontStyle: 'italic',
  },

  /* Sections */
  section: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 18,
    marginBottom: 12,
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
  },
  sectionHeading: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1B5E20',
    marginBottom: 12,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  bulletDot: {
    color: '#558B2F',
    fontSize: 16,
    fontWeight: '700',
    marginRight: 8,
    lineHeight: 20,
  },
  bulletText: {
    flex: 1,
    fontSize: 13,
    color: '#37474F',
    lineHeight: 20,
  },

  /* Footer */
  footer: {
    marginTop: 24,
    alignItems: 'center',
  },
  footerText: { fontSize: 11, color: '#78909C' },
});
